[ADD] ansible_base: Add core.role and other submodules
LasLabs/ansible-base pull request #1
Opened 2017-03-30 01:08 UTC by tedsalmon

2017-03-30 16:42 UTC, lasley requested changes

2017-03-30 16:42 UTC, lasley commented on .travis.yml
> +#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
Remove commented code

2017-03-30 16:42 UTC, lasley commented on README.md
> +
or `git clone --recursive $URI`

2017-03-30 16:42 UTC, lasley commented on README.md
> +Variables
Remove empty headers

2017-03-30 16:42 UTC, lasley commented on roles/core.role/defaults/main.yml
> +system_hostname: "ec2-xxxx-prod-vml-01.example.com"
Does this get applied to all servers in the playbook?

2017-03-30 16:42 UTC, lasley commented on roles/core.role/defaults/main.yml
> +fail2ban_config_jail_sshddos_enabled: yes
newline EOL

2017-03-30 16:42 UTC, lasley commented on roles/core.role/defaults/main.yml
> +fail2ban_config_jail_sshddos_enabled: yes
https://stackoverflow.com/questions/36043061/automatically-add-newline-on-save-in-pycharm

2017-03-30 16:42 UTC, lasley commented on roles/core.role/meta/main.yml
> +  description: Role allows you to provision a new Fedora 19+ Server
Fedora? I thought we were going to use CentOS?

2017-03-30 16:42 UTC, lasley commented on roles/core.role/tasks/apps.yml
> +
too many newlines

2017-03-30 16:42 UTC, lasley commented on roles/core.role/tasks/fail2ban.yml
> +  tags: configuration
newline eol

2017-03-30 16:42 UTC, lasley commented on roles/core.role/tasks/apps.yml
> +---
header

2017-03-30 16:42 UTC, lasley commented on roles/core.role/meta/main.yml
> +# Copyright 2016 LasLabs Inc.
2017

2017-03-30 16:42 UTC, lasley commented on roles/core.role/defaults/main.yml
>  ---
header

2017-03-30 16:42 UTC, lasley commented on roles/core.role/tasks/main.yml
> +
newline

2017-03-30 16:42 UTC, lasley commented on roles/core.role/tasks/preferences.yml
> +  file: path=/root/.ssh state=directory
nleol

2017-03-30 16:42 UTC, lasley commented on roles/core.role/tasks/sshd.yml
> +  notify: restart-sshd
nleol

2017-03-30 16:42 UTC, lasley commented on roles/core.role/templates/jail.local.j2
> +logpath  = /var/log/secure
nleol

2017-03-30 16:42 UTC, lasley commented on roles/core.role/tests/test.yml
> +    - core.role
nleol

2017-03-30 16:42 UTC, lasley commented on roles/core.role/tests/test.yml
>  - hosts: localhost
header

2017-03-30 16:42 UTC, lasley commented on vars/settings.vault.yml
> +# License Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.html).
nleol

2017-03-30 16:42 UTC, lasley commented on vars/settings.yml
> +# License Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0.html).
nleol

2017-03-30 19:56 UTC, tedsalmon commented on roles/core.role/meta/main.yml
> +  description: Role allows you to provision a new Fedora 19+ Server
CentOS is not a valid distro in Ansible terms. CentOS 7 is Fedora 19+ ;)

2017-03-30 20:34 UTC, tedsalmon commented on roles/core.role/defaults/main.yml
> +system_hostname: "ec2-xxxx-prod-vml-01.example.com"
I added a section about this in the README and removed the hostname default. It should be set in the inventory, per host.

2017-03-31 20:57 UTC, tedsalmon commented
Alright @lasley - Tests fixed and comments attended to :)

2017-03-31 21:15 UTC, lasley approved these changes

2017-03-31 21:15 UTC, merged